utils::globalVariables(c(".",
                         "Idx",
                         "IdxCol",
                         "IdxRow",
                         "Sort.Classifier",
                         "Well",
                         "bits",
                         "inputFCS",
                         "value"))